# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
osx_image: xcode8

script:
- xcodebuild clean test -project EBTExtractor.xcodeproj -scheme Extractor -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.2'
- xcodebuild clean test -project EBTExtractor.xcodeproj -scheme Extractor-OSX -sdk macosx ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.2'
